spring.datasource.url=jdbc:postgresql://localhost:5432/palace_game
spring.datasource.username=postgres
spring.datasource.password=palace_game
spring.datasource.driver-class-name=org.postgresql.Driver
